# Numpy Cheat Sheet

Before reading this notebook, make sure you read the absolute minimum introduction to the library: https://numpy.org/doc/stable/user/absolute_beginners.html

In [1]:
# That's how you import NumPy. Impressive, right ?
import numpy as np

### Array Creation
There are several ways to create an array with NumPy:

In [2]:
# Create an array from a list of values
A = np.array([1,2,3,4,5])
print('A = ', A)

# Create an array using np.arange
B = np.arange(5)
print('B = ', B)

# Create an array using np.zeros (or np.ones)
C = np.zeros(5)
print('C = ', C)

# Create an array of ones the same shape as A using np.ones_like (or np.zeros_like)
D = np.ones_like(A)
print('D = ', D)

A =  [1 2 3 4 5]
B =  [0 1 2 3 4]
C =  [0. 0. 0. 0. 0.]
D =  [1 1 1 1 1]


### Array casting
Arrays can be casted to a different type! Here's how:

In [3]:
# Use the dtype argument of np.array
E = np.array(D, dtype=float)
print('E = ', E)

# Use .astype method (anything different than 0 is converted to True)
F = B.astype(bool)
print('F = ', F)

E =  [1. 1. 1. 1. 1.]
F =  [False  True  True  True  True]


### Elementwise operations
Basic mathematical operations such as + - * / % ** are applied to each element of an array i.e. elementwise. Numpy uses **[Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)** to make these mathematical operations work, something you should already be familiar with having used Pandas DataFrames.  

In [4]:
# Create an array
A = np.array([1,2,3,4,5])
print('A = ', A)

# Add 2 to each element of the array
B = A + 2
print('B = A + 2 = ', B)

# Square each element of the array
C = A ** 2
print('C = A**2 = ', C)

# Elementwise sum: THIS CANNOT WORK IF A AND B DO NOT HAVE THE SAME SIZE!!
D = A + B
print('D = A + B = ', D)

# Elementwise multiplication: THIS CANNOT WORK IF A AND B DO NOT HAVE THE SAME SIZE!!
E = A * B
print('E = A * B = ', E)

# Elementwise exponential
F = np.exp(A)
print('F = np.exp(A) = ', F)

# Elementwise cosine
G = np.cos(A)
print('G = np.cos(A) = ', G)

# Elementwise square root
H = np.sqrt(A)
print('H = np.sqrt(A) = ', H)

A =  [1 2 3 4 5]
B = A + 2 =  [3 4 5 6 7]
C = A**2 =  [ 1  4  9 16 25]
D = A + B =  [ 4  6  8 10 12]
E = A * B =  [ 3  8 15 24 35]
F = np.exp(A) =  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
G = np.cos(A) =  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
H = np.sqrt(A) =  [1.         1.41421356 1.73205081 2.         2.23606798]


### Reduction operations
Some operations perform a **reduction**: they reduce the size or the dimension of the array! For example, summing all the values of an array *reduces* the array to a single number.

In [5]:
# Create an array
A = np.arange(1,11)
print('A = ', A)

# Let's count the sum of all the numbers up to 10
B = np.sum(A)
print('B = np.sum(A) = ', B)

# And the product (be careful, the product can easily overflow...)
C = np.prod(A)
print('C = np.prod(A) = ', C)

# Dot product: take the sum of the elementwise product of two arrays (also written A.B)
D = np.dot(A,A)
print('D = A.A = ', D)
print('np.sum(A*A) = ', np.sum(A*A))

# Take the minimum value of A
E = np.min(A)
print('E = np.min(A) = ', E)

# Take the maximum value of A
F = np.max(A)
print('F = np.max(A) = ', F)

# Take the index of the minimum value of A
G = np.argmin(A)
print('G = np.argmin(A) = ', G)

# Take the index of the maximum value of A
H = np.argmax(A)
print('H = np.argmax(A) = ', H)

A =  [ 1  2  3  4  5  6  7  8  9 10]
B = np.sum(A) =  55
C = np.prod(A) =  3628800
D = A.A =  385
np.sum(A*A) =  385
E = np.min(A) =  1
F = np.max(A) =  10
G = np.argmin(A) =  0
H = np.argmax(A) =  9


### Array indexing

In [6]:
A = np.array([1,2,3,4])
B = np.array([
            [0.0,0.1,0.2,0.3,0.4],
            [1.0,1.1,1.2,1.3,1.4],
            [2.0,2.1,2.2,2.3,2.4],
            ])
C = np.array([1,2,'3',4])

# Shape and type
print(A)
print(f"A.shape = {A.shape}")
print(f"A.ndim = {A.ndim}")
print(f"A.dtype = {A.dtype}")
print()
print(B)
print(f"B.shape = {B.shape}")
print(f"B.ndim = {B.ndim}")
print(f"B.dtype = {B.dtype}")
print()
print(C)
print(f"C.shape = {C.shape}")
print(f"C.ndim = {C.ndim}")
print(f"C.dtype = {C.dtype}")
print()

# Indexing
# Note that indexing begins at 0
print(f"A[0] = {A[0]}")
print(f"B[0] = {B[0]}")
print(f"B[0,1] = {B[0,1]}")
print()

# Slice extraction
print(f"B[0,:] = {B[0,:]}")
print(f"B[:,0] = {B[:,0]}")
print(f"B[0, 1:3] = {B[0, 1:3]}") # notice index 3 is excluded
print(f"B[0, 1:] = {B[0, 1:]}") # retreives all but one elements of the first nested array (from index=1 until the end)
print()

# Assignation
B[0,0] = 8
print(f"B[0,0] = 8 : \n{B}")
B[1,1:] = A
print(f"B[1,1:] = A : \n{B}")

[1 2 3 4]
A.shape = (4,)
A.ndim = 1
A.dtype = int32

[[0.  0.1 0.2 0.3 0.4]
 [1.  1.1 1.2 1.3 1.4]
 [2.  2.1 2.2 2.3 2.4]]
B.shape = (3, 5)
B.ndim = 2
B.dtype = float64

['1' '2' '3' '4']
C.shape = (4,)
C.ndim = 1
C.dtype = <U11

A[0] = 1
B[0] = [0.  0.1 0.2 0.3 0.4]
B[0,1] = 0.1

B[0,:] = [0.  0.1 0.2 0.3 0.4]
B[:,0] = [0. 1. 2.]
B[0, 1:3] = [0.1 0.2]
B[0, 1:] = [0.1 0.2 0.3 0.4]

B[0,0] = 8 : 
[[8.  0.1 0.2 0.3 0.4]
 [1.  1.1 1.2 1.3 1.4]
 [2.  2.1 2.2 2.3 2.4]]
B[1,1:] = A : 
[[8.  0.1 0.2 0.3 0.4]
 [1.  1.  2.  3.  4. ]
 [2.  2.1 2.2 2.3 2.4]]


### Array  masking

In [7]:
A = np.array([1,2,3,4])
mask = np.array([True, False, False, True])
print(A)
print(mask)
print("A[mask] = ",A[mask])

# Now use this to modify part of the array
A[mask] = 10
print("A[mask] = 10 : A = ",A)
print()

# A mask is generally a boolean test on another array

# set to 0 all values above 5 in A
A[A>5] = 0
print("A[A>5] = 0 : A = ",A)
print()

# Replace negative values in A by the value of B at that position
A = np.linspace(-1,1,5)
B = -2*A
print(f"A = {A}")
print(f"B = {B}")
A[A<0] = B[A<0]
print(f"A[A<0] = B[A<0]: A = {A}")

[1 2 3 4]
[ True False False  True]
A[mask] =  [1 4]
A[mask] = 10 : A =  [10  2  3 10]

A[A>5] = 0 : A =  [0 2 3 0]

A = [-1.  -0.5  0.   0.5  1. ]
B = [ 2.  1. -0. -1. -2.]
A[A<0] = B[A<0]: A = [2.  1.  0.  0.5 1. ]
